### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by D-Nice** [D-Nice/vindi#13]
* [x] Change workdir to vindi
* [x] Add bashrc alias guidance (did better, just made install script with
executable sh script as bin)
* [x] Add my defaults in, and provide guidance on how to override defaults or use
own profile.
* [x] ensure pywal profile applies... or look into what it'll take
* [ ] find something more elegant than the 2 minute wait for the coc extension
install to complete.
One way is to use CocInstall sync, but then the extensions need to be
explicitly declared in the
Dockerfile instead of the init.vim
OR read/ping stdout from nvim, and if no output after x time, consider it done?
or wait for expected last message to show up and continue
* [x] Look into minifying the docker image (try node:lts-slim ??)
* [x] Add NERDTree tab patch to re-use exisitng tab window instead of opening a
new one
* [x] Turn this into a table
* [x] Due to bad coloring for errors, either change their colour, or change
from floating windows - fixed for pywal
* [ ] Never leave it on the NERDTree window when tabbing through...
* [x] Look into solving apt install just failing on bad connection,
but silently (maybe multiple layers...). Used multiple layers.
* [x] fix coc-settings not showing wanted text signs
* [x] add keybindings to cycle through any found lsp issues
* [x] Populate some useful key list per plugin
* [x] Note that VS Code snippets can be added as plugins
* [x] Update docs with latest changes
* [x] Upload built image to Docker, ideally CI this process via GH actions
* [ ] Have install script check if vindi bin already exists, and ask for update instead?
* [ ] Minify in CI with docker-slim
* [ ] Use nicer icons for nerdtree-git-plugin if possibru?
* [ ] Look into persistence for some of the auto complete features or snippets
* [x] Persist command history between container and host
* [ ] If too ugly, move out BUGS/TODO
* [x] Make vindi usable with local build or remote image pull
* [ ] add xxd to image to be able to hexdump via :%!xxd
* [ ] investigate culprit for high cpu usage on large json file and any workarounds, and whether it is repeatable on other file types.
